FROM photon:4.0

ENV PGDATA /var/lib/postgresql/data

RUN tdnf install -y shadow gzip postgresql13 findutils bc >> /dev/null \
    && groupadd -r postgresql --gid=999 \
    && useradd -m -r -g postgres --uid=999 postgres \
    && mkdir -p /docker-entrypoint-initdb.d \
    && mkdir -p /run/postgresql \
    
RUN tdnf erase -y toybox && tdnf install -y util-linux net-tools
