swagger: '2.0'
info:
  title: Harbor API
  description: These APIs provide services for manipulating Harbor project.
  version: ''
host: localhost
schemes:
  - http
  - https
basePath: /api/
produces:
  - application/json
consumes:
  - application/json
securityDefinitions:
  basic:
    type: basic
security:
  - basic: []
  - {}
paths:
  /version:
    get:
      summary: Get API version
      description: Get the version of API that supported by the Harbor instance.
      tags:
        - Version
      responses:
        '200':
          description: The supported API version
          schema:
            type: object
            properties:
              version:
                type: string

  /chartrepo/health:
    get:
      summary: Check the health of chart repository service.
      description: Check the health of chart repository service.
      tags:
        - Chart Repository
      responses:
        '200':
          description: Health status of chart repository service is returned.
          schema:
            type: object
            properties:
              healthy:
                type: boolean
        '401':
          $ref: '#/definitions/UnauthorizedChartAPIError'
        '403':
          $ref: '#/definitions/ForbiddenChartAPIError'

definitions:
  ChartAPIError:
    description: The error object returned by chart repository API
    type: object
    required:
      - error
    properties:
      error:
        type: string
        description: The error message returned by the chart API
  UnauthorizedChartAPIError:
    description: Unauthorized
    type: object
    allOf:
      - $ref: '#/definitions/ChartAPIError'

  DigitalSignature:
    type: object
    description: The signature of the chart
    properties:
      signed:
        type: boolean
        description: A flag to indicate if the chart is signed
      prov_file:
        type: string
        description: The URL of the provance file